## Homework

### Part 1

#### Հաշվարկներ + Boolean

In [33]:
import matplotlib as mb
import pandas as pd

In [34]:
revenues = [130, 170, 210, 75, 300]
tax_rate = 0.20
discount_rate = 0.10

In [35]:
# tax
revenues_with_tax = [i * (1+ tax_rate) for i in revenues]

# final
final_revenues = i * (1 + tax_rate) * (1 - discount_rate)

# boolean
greater_150 = [i > 150 for i in revenues]
between_150_300 = [100 < i < 300 for i in revenues]

##### Փակագծերը կարևոր են նրա համար որ թվաբանական հաշվարկները ճիշտ կատարվեն

### Part 2

#### Loops

In [36]:
# Sum
total = 0
for i in revenues:
    total += i

print(total)

# average
avg = total / len(revenues)

print(avg)

# max
max = revenues[0]
for i in revenues:
    if i > max:
        max = i

print(max)

# count > 150
high_revenues = 0
for i in revenues:
    if i > 150:
        high_revenues += 1

print(high_revenues)

# commission
commission = [i * 1.05 for i in revenues]
commission

885
177.0
300
3

[136.5, 178.5, 220.5, 78.75, 315.0]

### Part 3

#### if / elif / else

In [50]:
revenues = [130, 170, 210, 75, 300]

In [58]:
segments = []

for i in revenues:
    i = int(i)

    if i > 200:
        segments.append("Premium")

    elif 100 < i <= 200:
        segments.append("Standart")
    else: 
        segments.append("Low")

print(segments)

['Standart', 'Standart', 'Premium', 'Low', 'Premium']

### Part 4

#### Set

In [86]:
customer_id = [1,2,3,4,5,6,7,4,2,5,6,3,9,8,0,3]

In [89]:
unique_id = set(customer_id)
new_l = list(unique_id)

new_l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [94]:
len_new_l = print(len(new_l))
len_customer_id = print(len(customer_id))

10
16

##### set-ը unordered է, որովհետև չի պահում հերթականությունը

### Part 5

#### Dictionary

In [119]:
customer = {
    "name": "Vahe", 
    "revenue": 700, 
    "city": "Hrazdan" 
}

In [120]:
customer['segment'] = "Premium"

In [121]:
customer["revenue"] = 1500

In [122]:
del customer["city"]

In [123]:
print(customer)

{'name': 'Vahe', 'revenue': 1500, 'segment': 'Premium'}

In [ ]:
for k, v in customer.items():
    print(k, v)

name Vahe
revenue 1500
segment Premium

### Part 6

#### List comprehension

In [140]:
new_l_1 = [i*2 for i in revenues]
new_l_2 = [i**2 for i in revenues]
new_l_3 = [i/2 for i in revenues]

In [141]:
print(new_l_1)
print(new_l_2)
print(new_l_3)

[260, 340, 420, 150, 600]
[16900, 28900, 44100, 5625, 90000]
[65.0, 85.0, 105.0, 37.5, 150.0]

##### list comprehension-ը ավելի կարճ ու արագ է loop-ից

### Part 7

#### Pandas

In [152]:
data = {"name": ["Vahe", "Arman", "Karen", "Hayk", "Vav"],
        "age": [22, 23, 20, 24, 22],
        "city": ["Hrazdan", "Hrazdan", "Sevan", "Yerevan", "London" ],
        "revenue": [300, 500, 250, 400, 700]
        }

In [154]:
df = pd.DataFrame(data)

In [155]:
df.head()

    name  age     city  revenue
0   Vahe   22  Hrazdan      300
1  Arman   23  Hrazdan      500
2  Karen   20    Sevan      250
3   Hayk   24  Yerevan      400
4    Vav   22   London      700

In [187]:
df["revenue_after_tax"] = df["revenue"] // 1.20

In [188]:
df.head()

    name  age     city  revenue  revenue_after_tax
0   Vahe   22  Hrazdan      300              250.0
1  Arman   23  Hrazdan      500              416.0
2  Karen   20    Sevan      250              208.0
3   Hayk   24  Yerevan      400              333.0
4    Vav   22   London      700              583.0

In [189]:
df_filtered = df[df["revenue"] > 400]

In [186]:
df = df.drop("revenue_after_tax", axis=1)

In [190]:
df.shape

(5, 5)

##### pandas-ը հեշտ է, որովհետև աշխատում է ամբողջ սյուների վրա միանգամից