In [5]:
import pandas as pd
pd.options.display.float_format = '{:.2f}'.format
import numpy as np

### Unzip

In [6]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

### Ֆայլերի Ներմուծում

#### orders.csv

In [7]:
df_orders = pd.read_csv("../data/raw/orders.csv")
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

#### products.csv

In [8]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

#### departments.csv

In [9]:
df_departments = pd.read_csv("../data/raw/departments.csv")
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

### Տվյալների ուսումնասիրություն Pandas-ով

#### Վերին տողերը (Top N rows)

In [10]:
df_products.head(3)
df_orders.head(2)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00

#### Վերջին տողերը

In [11]:
df_orders.tail(3)
df_products.tail(1)

       product_id            product_name  aisle_id  department_id  prices
49692       49688  Fresh Foaming Cleanser        73             11   13.50

#### Սյուների անուններ

In [12]:
df_products.columns
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

#### Տվյալների տիպեր

In [13]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [14]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

### Վիճակագրական ամփոփում

In [15]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3421083.00,3421083.00,3421083.00,3421083.00,3421083.00,3214874.00
mean,1710542.00,102978.21,17.15,2.78,13.45,11.11
std,987581.74,59533.72,17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,855271.50,51394.00,5.00,1.00,10.00,4.00
50%,1710542.00,102689.00,11.00,3.00,13.00,7.00
75%,2565812.50,154385.00,23.00,5.00,16.00,15.00
max,3421083.00,206209.00,100.00,6.00,23.00,30.00

### Data Wrangling և Subsetting

#### Սյուների ջնջում

In [16]:
df_orders_new = df_orders.drop(columns=["eval_set"])

In [17]:
df_orders.drop(columns=["eval_set"], inplace=True)

#### Սյուների անվանափոխում

In [18]:
df_orders_new = df_orders.rename(columns={"order_dow": "order_days_of_week"})

In [19]:
df_orders_new.head()

,order_id,user_id,order_number,order_days_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.00
2,473747,1,3,3,12,21.00
3,2254736,1,4,4,7,29.00
4,431534,1,5,4,15,28.00

In [20]:
df_orders.rename(columns={"order_dow": "order_days_of_week"}, inplace=True)

#### Տվյալների տիպերի փոփոխում

In [21]:
df_orders_new = df_orders.astype({"order_id": "int64"})

In [22]:
df_orders.astype({"order_id": "int64"})

,order_id,user_id,order_number,order_days_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.00
2,473747,1,3,3,12,21.00
3,2254736,1,4,4,7,29.00
4,431534,1,5,4,15,28.00
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.00
3421079,1854736,206209,11,4,10,30.00
3421080,626363,206209,12,1,12,18.00
3421081,2977660,206209,13,1,12,7.00
3421082,272231,206209,14,6,14,30.00

In [23]:
df_orders["order_id"] = df_orders["order_id"].astype("int64")

#### Տվյալների փոխակերպում

In [24]:
df_orders["is_weekend"] = df_orders["order_days_of_week"].isin([0, 6])
df_orders["is_morning"] = df_orders["order_hour_of_day"] < 12

In [25]:
df_orders["order_frequency_category"] = df_orders["order_number"].apply(
    lambda x: "New" if x == 1
    else "Low" if x <= 5
    else "High"
)

In [26]:
df_orders["days_since_prior_order"] = df_orders["days_since_prior_order"].fillna(0)

In [39]:
df_products = pd.read_csv('../data/raw/products.csv')
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [44]:
df_products.reset_index()

,index,product_id,product_name,department_id,prices
0,0,1,Chocolate Sandwich Cookies,19,5.80
1,1,2,All-Seasons Salt,13,9.30
2,2,3,Robust Golden Unsweetened Oolong Tea,7,4.50
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.50
4,4,5,Green Chile Anytime Sauce,13,4.30
...,...,...,...,...,...
49688,49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",5,5.30
49689,49689,49685,En Croute Roast Hazelnut Cranberry,1,3.10
49690,49690,49686,Artisan Baguette,3,7.80
49691,49691,49687,Smartblend Healthy Metabolism Dry Cat Food,8,4.70
49692,49692,49688,Fresh Foaming Cleanser,11,13.50

#### DataFrame Transpose (շրջում)

In [54]:
# load original
df_departments_raw = pd.read_csv('../data/raw/departments.csv')

# transpose
df_t = df_departments_raw.T

# reset index
df_t = df_t.reset_index()

# rename columns
df_t.columns = ['department_id', 'department']

# remove first row (header-like row)
df_t = df_t[df_t['department_id'] != 'department_id']

# convert types
df_t['department_id'] = df_t['department_id'].astype(int)

# reset index
df_t = df_t.reset_index(drop=True)

df_t.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [55]:
df_t.to_csv('../data/processed/departments_t.csv', index=False)

In [56]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

### Տվյալների արտահանում (Exporting the data)

#### Արտահանում CSV ֆայլի մեջ

In [30]:
df_orders.to_csv("../data/processed/orders_cleaned.csv", index=False)

df_products.to_csv("../data/processed/products_cleaned.csv", index=False)

df_departments.to_csv("../data/processed/departments_t.csv", index=False)

### Տարբերակ A — os.path

In [31]:
import os

# Տպում է current folder-ը
print("Current working directory:", os.getcwd())

# Ստեղծում է path
file_path = os.path.join("data", "file.xlsx")
print("Relative path:", file_path)

Current working directory: c:\aca\data_analytics_with_phyton\notebooks
Relative path: data\file.xlsx