## Loading Packages

In [1]:
import pandas as pd

## Importing Dataframes

In [3]:
df_orders = pd.read_csv('../data/raw/orders.csv')
print(df_orders.shape)
df_orders.head()

(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [4]:
df_orders['eval_set'].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [9]:
df_orders_train = df_orders[df_orders['eval_set'] == 'train']
print(df_orders_train.shape)
df_orders_train.head()

df_orders_train.to_csv('../data/processed/orders_train.csv', index=False)

(131209, 7)

In [10]:
del df_orders

In [13]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.shape)
df_products.head()

(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [14]:
df_customers = pd.read_csv('../data/raw/customers.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/customers.csv'

In [29]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.shape)
df_departments.head()

(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol