## Loading Packages

In [ ]:
import pandas as pd
# new_df = pd.merge(left_df,right_df, on = 'id', how = 'left')

## Part 1

### df_products + df_departrments

In [4]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.shape)
df_departments.head()

(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [6]:
df_products = pd.read_csv('../data/raw/products.csv')
print(df_products.shape)
df_products.head()

(49693, 5)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [ ]:
# Merge

df_departments_products = pd.merge(
    df_departments,
    df_products,
    on='department_id',
    how='left'
)

In [29]:
df_departments_products.head()

,department_id,department,product_id,product_name,aisle_id,prices
0,1,frozen,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,10.5
1,1,frozen,8,Cut Russet Potatoes Steam N' Mash,116,1.1
2,1,frozen,12,Chocolate Fudge Layer Cake,119,9.4
3,1,frozen,18,Pizza for One Suprema Frozen Pizza,79,10.6
4,1,frozen,30,"Three Cheese Ziti, Marinara with Meatballs",38,13.8

### Քանի՞ ապրանք կա յուրաքանչյուր բաժնում (department)

In [24]:

df_departments_products["department"].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [44]:
df_departments_products["product_name"].describe()

count          49677
unique         49672
top       Ranger IPA
freq               2
Name: product_name, dtype: object

In [36]:
df_departments_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  49693 non-null  int64
 1   department     49693 non-null  str
 2   product_id     49693 non-null  int64
 3   product_name   49677 non-null  str
 4   aisle_id       49693 non-null  int64
 5   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 4.2 MB

### df_products_departments + df_aisles

In [45]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.shape)
df_aisles.head()

(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [49]:
# Merge

df_products_enriched = pd.merge(
    df_departments_products,
    df_aisles,
    on='aisle_id',
    how='left'
)

df_products_enriched.head()

,department_id,department,product_id,product_name,aisle_id,prices,aisle
0,1,frozen,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,10.5,frozen meals
1,1,frozen,8,Cut Russet Potatoes Steam N' Mash,116,1.1,frozen produce
2,1,frozen,12,Chocolate Fudge Layer Cake,119,9.4,frozen dessert
3,1,frozen,18,Pizza for One Suprema Frozen Pizza,79,10.6,frozen pizza
4,1,frozen,30,"Three Cheese Ziti, Marinara with Meatballs",38,13.8,frozen meals

In [52]:
# Cheking _merge
df_products_enriched_check = pd.merge(
    df_departments_products,
    df_aisles,
    on='aisle_id',
    how='left',
    indicator=True
)

df_products_enriched_check['_merge'].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

#### Uniqueness ստուգում

In [53]:
df_departments['department_id'].is_unique
df_aisles['aisle_id'].is_unique

True

## Part 2

### Քանի՞ ապրանք կա յուրաքանչյուր aisle-ում

In [ ]:
df_products_enriched['aisle'].value_counts().head()

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
Name: count, dtype: int64

### Products by Departament

In [ ]:
df_products_enriched['department'].value_counts().head()

department
personal care    6565
snacks           6264
pantry           5371
beverages        4365
frozen           4007
Name: count, dtype: int64

In [65]:
df_orders_products_train = pd.read_csv('../data/raw/orders.csv')
print(df_orders_products_train.shape)
df_orders_products_train.head()

(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [62]:
df_orders_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_train.shape)
df_orders_train.head()

(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [ ]:
# Merge

df_orders_info = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on='order_id',
    how='left'
)

df_orders_info.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,1,49302,1,1,112108,train,4,4,10,9.0
1,1,11109,2,1,112108,train,4,4,10,9.0
2,1,10246,3,0,112108,train,4,4,10,9.0
3,1,49683,4,0,112108,train,4,4,10,9.0
4,1,43633,5,1,112108,train,4,4,10,9.0

In [ ]:
# Merge check

df_orders_info_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on='order_id',
    how='left',
    indicator=True
)

### Indicator ստուգում

In [72]:
df_orders_info_check["_merge"].value_counts()

_merge
both          1384617
left_only           0
right_only          0
Name: count, dtype: int64

### Տողերի ստուգում

In [73]:
print(df_orders_train.shape)
print(df_orders_products_train.shape)
print(df_orders_info.shape)

(1384617, 4)
(3421083, 7)
(1384617, 10)

## Part 3

### Վաճառքը ըստ պատվերի թվի

In [76]:
df_orders_info['order_number'].value_counts().head()

order_number
4    149882
5    123548
6    105328
7     90949
8     75645
Name: count, dtype: int64

### Basket Size

In [95]:
df_orders_info.groupby("order_id").size().sort_values(ascending=False)

order_id
2813632    80
1395075    80
949182     77
2869702    76
341238     76
           ..
1231029     1
1230813     1
2473878     1
3420798     1
1932460     1
Length: 131209, dtype: int64

### Միջին արժեքներ

In [86]:
df_orders_info.groupby("order_id").size().describe()

count    131209.000000
mean         10.552759
std           7.932847
min           1.000000
25%           5.000000
50%           9.000000
75%          14.000000
max          80.000000
dtype: float64

### Basket size - ի միջինը

In [87]:
df_orders_info.groupby("order_id").size().mean()

np.float64(10.552759338155157)

### Միջին basket ըստ օրվա

In [96]:
df_orders_info.groupby('order_dow')['reordered'].mean()

order_dow
0    0.609624
1    0.598977
2    0.588365
3    0.586724
4    0.594632
5    0.606178
6    0.594238
Name: reordered, dtype: float64

In [99]:
# Merge

df_train_analytics = pd.merge(
    df_orders_info,
    df_products_enriched,
    on='product_id',
    how='left'
)

df_train_analytics.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,department_id,department,product_name,aisle_id,prices,aisle
0,1,49302,1,1,112108,train,4,4,10,9.0,16.0,dairy eggs,Bulgarian Yogurt,120.0,9.1,yogurt
1,1,11109,2,1,112108,train,4,4,10,9.0,16.0,dairy eggs,Organic 4% Milk Fat Whole Milk Cottage Cheese,108.0,2.0,other creams cheeses
2,1,10246,3,0,112108,train,4,4,10,9.0,4.0,produce,Organic Celery Hearts,83.0,4.5,fresh vegetables
3,1,49683,4,0,112108,train,4,4,10,9.0,4.0,produce,Cucumber Kirby,83.0,13.2,fresh vegetables
4,1,43633,5,1,112108,train,4,4,10,9.0,15.0,canned goods,Lightly Smoked Sardines in Olive Oil,95.0,1.7,canned meat seafood

In [100]:
df_train_analytic_check = pd.merge(
    df_orders_info,
    df_products_enriched,
    on='product_id',
    how='left',
    indicator=True
)

In [101]:
df_train_analytic_check["_merge"].value_counts()

_merge
both          1384618
left_only          88
right_only          0
Name: count, dtype: int64

## Part 4

### Ամենաշատ գնվող ապրանքներ

In [102]:
df_train_analytics["product_name"].value_counts().head()

product_name
Banana                    18726
Bag of Organic Bananas    15480
Organic Strawberries      10894
Organic Baby Spinach       9784
Large Lemon                8135
Name: count, dtype: int64

### Reorder rate ըստ բաժնի

In [104]:
df_train_analytics.groupby("department")["reordered"].mean()

department
alcohol            0.606748
babies             0.541062
bakery             0.634211
beverages          0.658132
breakfast          0.571806
bulk               0.578366
canned goods       0.486805
dairy eggs         0.674966
deli               0.617891
dry goods pasta    0.487821
frozen             0.559297
household          0.427166
international      0.379936
meat seafood       0.590854
missing            0.381530
other              0.388301
pantry             0.363088
personal care      0.337516
pets               0.630198
produce            0.664617
snacks             0.581363
Name: reordered, dtype: float64

### Cross-tab

In [105]:
pd.crosstab(
    df_train_analytics["department"],
    df_train_analytics["reordered"]
)

reordered             0       1
department
alcohol            2203    3399
babies             6857    8084
bakery            17702   30692
beverages         38960   75002
breakfast         12654   16898
bulk                573     786
canned goods      24017   22782
dairy eggs        70549  146502
deli              16924   27367
dry goods pasta   19828   18885
frozen            44258   56168
household         20614   15372
international      7380    4522
meat seafood      12400   17907
missing            5103    3148
other              1098     697
pantry            51744   29498
personal care     14309    7290
pets               1663    2834
produce          137201  271886
snacks            49760   69102